version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000/shell/ || exit 1']
      interval: 1s
      timeout: 10s
      retries: 3
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-inMemory']
    expose:
      - '8000'
